run:
  deadline: 5m
  skip-files: [ ]
  skip-dirs: [ ]

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  goconst:
    min-len: 5
    min-occurrences: 3
  misspell:
    locale: US
  funlen:
    lines: -1
    statements: 50
  godox:
    keywords:
      - FIXME
  gofumpt:
    extra-rules: true
  depguard:
    list-type: blacklist
    include-go-root: false
    packages:
      - github.com/sirupsen/logrus
      - github.com/pkg/errors
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - sloppyReassign
      - unnamedResult
      - hugeParam
      - rangeValCopy
      - octalLiteral
      - paramTypeCombine # already handle by gofumpt.extra-rules

linters:
  enable-all: true
  disable:
    - deadcode # deprecated
    - exhaustivestruct # deprecated
    - golint # deprecated
    - ifshort # deprecated
    - interfacer # deprecated
    - maligned # deprecated
    - nosnakecase # deprecated
    - scopelint # deprecated
    - scopelint # deprecated
    - structcheck # deprecated
    - varcheck # deprecated
    - sqlclosecheck # not relevant (SQL)
    - rowserrcheck # not relevant (SQL)
    - execinquery # not relevant (SQL)
    - cyclop # duplicate of gocyclo
    - lll
    - dupl
    - gomnd
    - tparallel
    - paralleltest
    - testpackage
    - goerr113
    - wrapcheck
    - nlreturn
    - wsl
    - exhaustive
    - exhaustruct
    - prealloc
    - noctx
    - varnamelen
    - ireturn
    - contextcheck
    - nosnakecase
    - varnamelen
    - nonamedreturns

issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0
  exclude:
    - 'ST1000: at least one file in a package should have a package comment'
    - 'package-comments: should have a package comment'
    - 'G114: Use of net/http serve function that has no support for setting timeouts'
  exclude-rules:
    - path: version.go
      text: '`(version|date|commit)` is a global variable'
    - path: .*_test.go
      linters:
        - funlen
        - unused
        - maintidx
    - path: pkg/handlers/module.go
      text: Function 'Download' is too long (.*)
    - path: pkg/handlers/module.go
      text: Function 'downloadGoProxy' is too long (.*)
    - path: pkg/handlers/module.go
      text: Function 'downloadGitHub' is too long (.*)
    - path: pkg/functions/public.go
      text: Function 'Public' is too long (.*)
    - path: main.go
      text: Function 'serveCommand' is too long (.*)
    - path: pkg/handlers/module.go
      text: Function 'Download' has too many statements (.*)
    - path: cmd/serve/serve.go
      text: 'cyclomatic complexity [0-9]* of func `setupEnvVars` is high (.*)'
    - path: pkg/db/mongodb/plugindb.go
      text: Function 'SearchByName' is too long
    - path: internal/token/token.go
      text: "json\\(camel\\): got 'userID' want 'userId'"
