// Code generated by mocktail; DO NOT EDIT.

package handlers

import (
	"context"
	"io"
	"net/http"
	"net/url"
	"testing"
	"time"

	"github.com/google/go-github/v57/github"
	"github.com/stretchr/testify/mock"
	"github.com/traefik/plugin-service/pkg/db"
	"golang.org/x/mod/modfile"
)

// githubPluginClientMock mock of GithubPluginClient.
type githubPluginClientMock struct{ mock.Mock }

// NewGithubPluginClientMock creates a new githubPluginClientMock.
func NewGithubPluginClientMock(tb testing.TB) *githubPluginClientMock {
	tb.Helper()

	m := &githubPluginClientMock{}
	m.Mock.Test(tb)

	tb.Cleanup(func() { m.AssertExpectations(tb) })

	return m
}

func (_m *githubPluginClientMock) Do(_ context.Context, req *http.Request, v interface{}) (*github.Response, error) {
	_ret := _m.Called(req, v)

	if _rf, ok := _ret.Get(0).(func(*http.Request, interface{}) (*github.Response, error)); ok {
		return _rf(req, v)
	}

	_ra0, _ := _ret.Get(0).(*github.Response)
	_rb1 := _ret.Error(1)

	return _ra0, _rb1
}

func (_m *githubPluginClientMock) OnDo(req *http.Request, v interface{}) *githubPluginClientDoCall {
	return &githubPluginClientDoCall{Call: _m.Mock.On("Do", req, v), Parent: _m}
}

func (_m *githubPluginClientMock) OnDoRaw(req interface{}, v interface{}) *githubPluginClientDoCall {
	return &githubPluginClientDoCall{Call: _m.Mock.On("Do", req, v), Parent: _m}
}

type githubPluginClientDoCall struct {
	*mock.Call
	Parent *githubPluginClientMock
}

func (_c *githubPluginClientDoCall) Panic(msg string) *githubPluginClientDoCall {
	_c.Call = _c.Call.Panic(msg)
	return _c
}

func (_c *githubPluginClientDoCall) Once() *githubPluginClientDoCall {
	_c.Call = _c.Call.Once()
	return _c
}

func (_c *githubPluginClientDoCall) Twice() *githubPluginClientDoCall {
	_c.Call = _c.Call.Twice()
	return _c
}

func (_c *githubPluginClientDoCall) Times(i int) *githubPluginClientDoCall {
	_c.Call = _c.Call.Times(i)
	return _c
}

func (_c *githubPluginClientDoCall) WaitUntil(w <-chan time.Time) *githubPluginClientDoCall {
	_c.Call = _c.Call.WaitUntil(w)
	return _c
}

func (_c *githubPluginClientDoCall) After(d time.Duration) *githubPluginClientDoCall {
	_c.Call = _c.Call.After(d)
	return _c
}

func (_c *githubPluginClientDoCall) Run(fn func(args mock.Arguments)) *githubPluginClientDoCall {
	_c.Call = _c.Call.Run(fn)
	return _c
}

func (_c *githubPluginClientDoCall) Maybe() *githubPluginClientDoCall {
	_c.Call = _c.Call.Maybe()
	return _c
}

func (_c *githubPluginClientDoCall) TypedReturns(a *github.Response, b error) *githubPluginClientDoCall {
	_c.Call = _c.Return(a, b)
	return _c
}

func (_c *githubPluginClientDoCall) ReturnsFn(fn func(*http.Request, interface{}) (*github.Response, error)) *githubPluginClientDoCall {
	_c.Call = _c.Return(fn)
	return _c
}

func (_c *githubPluginClientDoCall) TypedRun(fn func(*http.Request, interface{})) *githubPluginClientDoCall {
	_c.Call = _c.Call.Run(func(args mock.Arguments) {
		_req, _ := args.Get(0).(*http.Request)
		_v, _ := args.Get(1).(interface{})
		fn(_req, _v)
	})
	return _c
}

func (_c *githubPluginClientDoCall) OnDo(req *http.Request, v interface{}) *githubPluginClientDoCall {
	return _c.Parent.OnDo(req, v)
}

func (_c *githubPluginClientDoCall) OnGetArchiveLink(owner string, repo string, archiveformat github.ArchiveFormat, opts *github.RepositoryContentGetOptions, maxRedirects int) *githubPluginClientGetArchiveLinkCall {
	return _c.Parent.OnGetArchiveLink(owner, repo, archiveformat, opts, maxRedirects)
}

func (_c *githubPluginClientDoCall) OnGetReleaseByTag(owner string, repo string, tag string) *githubPluginClientGetReleaseByTagCall {
	return _c.Parent.OnGetReleaseByTag(owner, repo, tag)
}

func (_c *githubPluginClientDoCall) OnDoRaw(req interface{}, v interface{}) *githubPluginClientDoCall {
	return _c.Parent.OnDoRaw(req, v)
}

func (_c *githubPluginClientDoCall) OnGetArchiveLinkRaw(owner interface{}, repo interface{}, archiveformat interface{}, opts interface{}, maxRedirects interface{}) *githubPluginClientGetArchiveLinkCall {
	return _c.Parent.OnGetArchiveLinkRaw(owner, repo, archiveformat, opts, maxRedirects)
}

func (_c *githubPluginClientDoCall) OnGetReleaseByTagRaw(owner interface{}, repo interface{}, tag interface{}) *githubPluginClientGetReleaseByTagCall {
	return _c.Parent.OnGetReleaseByTagRaw(owner, repo, tag)
}

func (_m *githubPluginClientMock) GetArchiveLink(_ context.Context, owner string, repo string, archiveformat github.ArchiveFormat, opts *github.RepositoryContentGetOptions, maxRedirects int) (*url.URL, *github.Response, error) {
	_ret := _m.Called(owner, repo, archiveformat, opts, maxRedirects)

	if _rf, ok := _ret.Get(0).(func(string, string, github.ArchiveFormat, *github.RepositoryContentGetOptions, int) (*url.URL, *github.Response, error)); ok {
		return _rf(owner, repo, archiveformat, opts, maxRedirects)
	}

	_ra0, _ := _ret.Get(0).(*url.URL)
	_rb1, _ := _ret.Get(1).(*github.Response)
	_rc2 := _ret.Error(2)

	return _ra0, _rb1, _rc2
}

func (_m *githubPluginClientMock) OnGetArchiveLink(owner string, repo string, archiveformat github.ArchiveFormat, opts *github.RepositoryContentGetOptions, maxRedirects int) *githubPluginClientGetArchiveLinkCall {
	return &githubPluginClientGetArchiveLinkCall{Call: _m.Mock.On("GetArchiveLink", owner, repo, archiveformat, opts, maxRedirects), Parent: _m}
}

func (_m *githubPluginClientMock) OnGetArchiveLinkRaw(owner interface{}, repo interface{}, archiveformat interface{}, opts interface{}, maxRedirects interface{}) *githubPluginClientGetArchiveLinkCall {
	return &githubPluginClientGetArchiveLinkCall{Call: _m.Mock.On("GetArchiveLink", owner, repo, archiveformat, opts, maxRedirects), Parent: _m}
}

type githubPluginClientGetArchiveLinkCall struct {
	*mock.Call
	Parent *githubPluginClientMock
}

func (_c *githubPluginClientGetArchiveLinkCall) Panic(msg string) *githubPluginClientGetArchiveLinkCall {
	_c.Call = _c.Call.Panic(msg)
	return _c
}

func (_c *githubPluginClientGetArchiveLinkCall) Once() *githubPluginClientGetArchiveLinkCall {
	_c.Call = _c.Call.Once()
	return _c
}

func (_c *githubPluginClientGetArchiveLinkCall) Twice() *githubPluginClientGetArchiveLinkCall {
	_c.Call = _c.Call.Twice()
	return _c
}

func (_c *githubPluginClientGetArchiveLinkCall) Times(i int) *githubPluginClientGetArchiveLinkCall {
	_c.Call = _c.Call.Times(i)
	return _c
}

func (_c *githubPluginClientGetArchiveLinkCall) WaitUntil(w <-chan time.Time) *githubPluginClientGetArchiveLinkCall {
	_c.Call = _c.Call.WaitUntil(w)
	return _c
}

func (_c *githubPluginClientGetArchiveLinkCall) After(d time.Duration) *githubPluginClientGetArchiveLinkCall {
	_c.Call = _c.Call.After(d)
	return _c
}

func (_c *githubPluginClientGetArchiveLinkCall) Run(fn func(args mock.Arguments)) *githubPluginClientGetArchiveLinkCall {
	_c.Call = _c.Call.Run(fn)
	return _c
}

func (_c *githubPluginClientGetArchiveLinkCall) Maybe() *githubPluginClientGetArchiveLinkCall {
	_c.Call = _c.Call.Maybe()
	return _c
}

func (_c *githubPluginClientGetArchiveLinkCall) TypedReturns(a *url.URL, b *github.Response, c error) *githubPluginClientGetArchiveLinkCall {
	_c.Call = _c.Return(a, b, c)
	return _c
}

func (_c *githubPluginClientGetArchiveLinkCall) ReturnsFn(fn func(string, string, github.ArchiveFormat, *github.RepositoryContentGetOptions, int) (*url.URL, *github.Response, error)) *githubPluginClientGetArchiveLinkCall {
	_c.Call = _c.Return(fn)
	return _c
}

func (_c *githubPluginClientGetArchiveLinkCall) TypedRun(fn func(string, string, github.ArchiveFormat, *github.RepositoryContentGetOptions, int)) *githubPluginClientGetArchiveLinkCall {
	_c.Call = _c.Call.Run(func(args mock.Arguments) {
		_owner := args.String(0)
		_repo := args.String(1)
		_archiveformat, _ := args.Get(2).(github.ArchiveFormat)
		_opts, _ := args.Get(3).(*github.RepositoryContentGetOptions)
		_maxRedirects := args.Int(4)
		fn(_owner, _repo, _archiveformat, _opts, _maxRedirects)
	})
	return _c
}

func (_c *githubPluginClientGetArchiveLinkCall) OnDo(req *http.Request, v interface{}) *githubPluginClientDoCall {
	return _c.Parent.OnDo(req, v)
}

func (_c *githubPluginClientGetArchiveLinkCall) OnGetArchiveLink(owner string, repo string, archiveformat github.ArchiveFormat, opts *github.RepositoryContentGetOptions, maxRedirects int) *githubPluginClientGetArchiveLinkCall {
	return _c.Parent.OnGetArchiveLink(owner, repo, archiveformat, opts, maxRedirects)
}

func (_c *githubPluginClientGetArchiveLinkCall) OnGetReleaseByTag(owner string, repo string, tag string) *githubPluginClientGetReleaseByTagCall {
	return _c.Parent.OnGetReleaseByTag(owner, repo, tag)
}

func (_c *githubPluginClientGetArchiveLinkCall) OnDoRaw(req interface{}, v interface{}) *githubPluginClientDoCall {
	return _c.Parent.OnDoRaw(req, v)
}

func (_c *githubPluginClientGetArchiveLinkCall) OnGetArchiveLinkRaw(owner interface{}, repo interface{}, archiveformat interface{}, opts interface{}, maxRedirects interface{}) *githubPluginClientGetArchiveLinkCall {
	return _c.Parent.OnGetArchiveLinkRaw(owner, repo, archiveformat, opts, maxRedirects)
}

func (_c *githubPluginClientGetArchiveLinkCall) OnGetReleaseByTagRaw(owner interface{}, repo interface{}, tag interface{}) *githubPluginClientGetReleaseByTagCall {
	return _c.Parent.OnGetReleaseByTagRaw(owner, repo, tag)
}

func (_m *githubPluginClientMock) GetReleaseByTag(_ context.Context, owner string, repo string, tag string) (*github.RepositoryRelease, *github.Response, error) {
	_ret := _m.Called(owner, repo, tag)

	if _rf, ok := _ret.Get(0).(func(string, string, string) (*github.RepositoryRelease, *github.Response, error)); ok {
		return _rf(owner, repo, tag)
	}

	_ra0, _ := _ret.Get(0).(*github.RepositoryRelease)
	_rb1, _ := _ret.Get(1).(*github.Response)
	_rc2 := _ret.Error(2)

	return _ra0, _rb1, _rc2
}

func (_m *githubPluginClientMock) OnGetReleaseByTag(owner string, repo string, tag string) *githubPluginClientGetReleaseByTagCall {
	return &githubPluginClientGetReleaseByTagCall{Call: _m.Mock.On("GetReleaseByTag", owner, repo, tag), Parent: _m}
}

func (_m *githubPluginClientMock) OnGetReleaseByTagRaw(owner interface{}, repo interface{}, tag interface{}) *githubPluginClientGetReleaseByTagCall {
	return &githubPluginClientGetReleaseByTagCall{Call: _m.Mock.On("GetReleaseByTag", owner, repo, tag), Parent: _m}
}

type githubPluginClientGetReleaseByTagCall struct {
	*mock.Call
	Parent *githubPluginClientMock
}

func (_c *githubPluginClientGetReleaseByTagCall) Panic(msg string) *githubPluginClientGetReleaseByTagCall {
	_c.Call = _c.Call.Panic(msg)
	return _c
}

func (_c *githubPluginClientGetReleaseByTagCall) Once() *githubPluginClientGetReleaseByTagCall {
	_c.Call = _c.Call.Once()
	return _c
}

func (_c *githubPluginClientGetReleaseByTagCall) Twice() *githubPluginClientGetReleaseByTagCall {
	_c.Call = _c.Call.Twice()
	return _c
}

func (_c *githubPluginClientGetReleaseByTagCall) Times(i int) *githubPluginClientGetReleaseByTagCall {
	_c.Call = _c.Call.Times(i)
	return _c
}

func (_c *githubPluginClientGetReleaseByTagCall) WaitUntil(w <-chan time.Time) *githubPluginClientGetReleaseByTagCall {
	_c.Call = _c.Call.WaitUntil(w)
	return _c
}

func (_c *githubPluginClientGetReleaseByTagCall) After(d time.Duration) *githubPluginClientGetReleaseByTagCall {
	_c.Call = _c.Call.After(d)
	return _c
}

func (_c *githubPluginClientGetReleaseByTagCall) Run(fn func(args mock.Arguments)) *githubPluginClientGetReleaseByTagCall {
	_c.Call = _c.Call.Run(fn)
	return _c
}

func (_c *githubPluginClientGetReleaseByTagCall) Maybe() *githubPluginClientGetReleaseByTagCall {
	_c.Call = _c.Call.Maybe()
	return _c
}

func (_c *githubPluginClientGetReleaseByTagCall) TypedReturns(a *github.RepositoryRelease, b *github.Response, c error) *githubPluginClientGetReleaseByTagCall {
	_c.Call = _c.Return(a, b, c)
	return _c
}

func (_c *githubPluginClientGetReleaseByTagCall) ReturnsFn(fn func(string, string, string) (*github.RepositoryRelease, *github.Response, error)) *githubPluginClientGetReleaseByTagCall {
	_c.Call = _c.Return(fn)
	return _c
}

func (_c *githubPluginClientGetReleaseByTagCall) TypedRun(fn func(string, string, string)) *githubPluginClientGetReleaseByTagCall {
	_c.Call = _c.Call.Run(func(args mock.Arguments) {
		_owner := args.String(0)
		_repo := args.String(1)
		_tag := args.String(2)
		fn(_owner, _repo, _tag)
	})
	return _c
}

func (_c *githubPluginClientGetReleaseByTagCall) OnDo(req *http.Request, v interface{}) *githubPluginClientDoCall {
	return _c.Parent.OnDo(req, v)
}

func (_c *githubPluginClientGetReleaseByTagCall) OnGetArchiveLink(owner string, repo string, archiveformat github.ArchiveFormat, opts *github.RepositoryContentGetOptions, maxRedirects int) *githubPluginClientGetArchiveLinkCall {
	return _c.Parent.OnGetArchiveLink(owner, repo, archiveformat, opts, maxRedirects)
}

func (_c *githubPluginClientGetReleaseByTagCall) OnGetReleaseByTag(owner string, repo string, tag string) *githubPluginClientGetReleaseByTagCall {
	return _c.Parent.OnGetReleaseByTag(owner, repo, tag)
}

func (_c *githubPluginClientGetReleaseByTagCall) OnDoRaw(req interface{}, v interface{}) *githubPluginClientDoCall {
	return _c.Parent.OnDoRaw(req, v)
}

func (_c *githubPluginClientGetReleaseByTagCall) OnGetArchiveLinkRaw(owner interface{}, repo interface{}, archiveformat interface{}, opts interface{}, maxRedirects interface{}) *githubPluginClientGetArchiveLinkCall {
	return _c.Parent.OnGetArchiveLinkRaw(owner, repo, archiveformat, opts, maxRedirects)
}

func (_c *githubPluginClientGetReleaseByTagCall) OnGetReleaseByTagRaw(owner interface{}, repo interface{}, tag interface{}) *githubPluginClientGetReleaseByTagCall {
	return _c.Parent.OnGetReleaseByTagRaw(owner, repo, tag)
}

// pluginStorerMock mock of PluginStorer.
type pluginStorerMock struct{ mock.Mock }

// NewPluginStorerMock creates a new pluginStorerMock.
func NewPluginStorerMock(tb testing.TB) *pluginStorerMock {
	tb.Helper()

	m := &pluginStorerMock{}
	m.Mock.Test(tb)

	tb.Cleanup(func() { m.AssertExpectations(tb) })

	return m
}

func (_m *pluginStorerMock) Create(_ context.Context, bParam db.Plugin) (db.Plugin, error) {
	_ret := _m.Called(bParam)

	if _rf, ok := _ret.Get(0).(func(db.Plugin) (db.Plugin, error)); ok {
		return _rf(bParam)
	}

	_ra0, _ := _ret.Get(0).(db.Plugin)
	_rb1 := _ret.Error(1)

	return _ra0, _rb1
}

func (_m *pluginStorerMock) OnCreate(bParam db.Plugin) *pluginStorerCreateCall {
	return &pluginStorerCreateCall{Call: _m.Mock.On("Create", bParam), Parent: _m}
}

func (_m *pluginStorerMock) OnCreateRaw(bParam interface{}) *pluginStorerCreateCall {
	return &pluginStorerCreateCall{Call: _m.Mock.On("Create", bParam), Parent: _m}
}

type pluginStorerCreateCall struct {
	*mock.Call
	Parent *pluginStorerMock
}

func (_c *pluginStorerCreateCall) Panic(msg string) *pluginStorerCreateCall {
	_c.Call = _c.Call.Panic(msg)
	return _c
}

func (_c *pluginStorerCreateCall) Once() *pluginStorerCreateCall {
	_c.Call = _c.Call.Once()
	return _c
}

func (_c *pluginStorerCreateCall) Twice() *pluginStorerCreateCall {
	_c.Call = _c.Call.Twice()
	return _c
}

func (_c *pluginStorerCreateCall) Times(i int) *pluginStorerCreateCall {
	_c.Call = _c.Call.Times(i)
	return _c
}

func (_c *pluginStorerCreateCall) WaitUntil(w <-chan time.Time) *pluginStorerCreateCall {
	_c.Call = _c.Call.WaitUntil(w)
	return _c
}

func (_c *pluginStorerCreateCall) After(d time.Duration) *pluginStorerCreateCall {
	_c.Call = _c.Call.After(d)
	return _c
}

func (_c *pluginStorerCreateCall) Run(fn func(args mock.Arguments)) *pluginStorerCreateCall {
	_c.Call = _c.Call.Run(fn)
	return _c
}

func (_c *pluginStorerCreateCall) Maybe() *pluginStorerCreateCall {
	_c.Call = _c.Call.Maybe()
	return _c
}

func (_c *pluginStorerCreateCall) TypedReturns(a db.Plugin, b error) *pluginStorerCreateCall {
	_c.Call = _c.Return(a, b)
	return _c
}

func (_c *pluginStorerCreateCall) ReturnsFn(fn func(db.Plugin) (db.Plugin, error)) *pluginStorerCreateCall {
	_c.Call = _c.Return(fn)
	return _c
}

func (_c *pluginStorerCreateCall) TypedRun(fn func(db.Plugin)) *pluginStorerCreateCall {
	_c.Call = _c.Call.Run(func(args mock.Arguments) {
		_bParam, _ := args.Get(0).(db.Plugin)
		fn(_bParam)
	})
	return _c
}

func (_c *pluginStorerCreateCall) OnCreate(bParam db.Plugin) *pluginStorerCreateCall {
	return _c.Parent.OnCreate(bParam)
}

func (_c *pluginStorerCreateCall) OnCreateHash(module string, version string, hash string) *pluginStorerCreateHashCall {
	return _c.Parent.OnCreateHash(module, version, hash)
}

func (_c *pluginStorerCreateCall) OnDelete(id string) *pluginStorerDeleteCall {
	return _c.Parent.OnDelete(id)
}

func (_c *pluginStorerCreateCall) OnGet(id string) *pluginStorerGetCall {
	return _c.Parent.OnGet(id)
}

func (_c *pluginStorerCreateCall) OnGetByName(bParam string, cParam bool, dParam bool) *pluginStorerGetByNameCall {
	return _c.Parent.OnGetByName(bParam, cParam, dParam)
}

func (_c *pluginStorerCreateCall) OnGetHashByName(module string, version string) *pluginStorerGetHashByNameCall {
	return _c.Parent.OnGetHashByName(module, version)
}

func (_c *pluginStorerCreateCall) OnList(bParam db.Pagination) *pluginStorerListCall {
	return _c.Parent.OnList(bParam)
}

func (_c *pluginStorerCreateCall) OnSearchByName(bParam string, cParam db.Pagination) *pluginStorerSearchByNameCall {
	return _c.Parent.OnSearchByName(bParam, cParam)
}

func (_c *pluginStorerCreateCall) OnUpdate(bParam string, cParam db.Plugin) *pluginStorerUpdateCall {
	return _c.Parent.OnUpdate(bParam, cParam)
}

func (_c *pluginStorerCreateCall) OnCreateRaw(bParam interface{}) *pluginStorerCreateCall {
	return _c.Parent.OnCreateRaw(bParam)
}

func (_c *pluginStorerCreateCall) OnCreateHashRaw(module interface{}, version interface{}, hash interface{}) *pluginStorerCreateHashCall {
	return _c.Parent.OnCreateHashRaw(module, version, hash)
}

func (_c *pluginStorerCreateCall) OnDeleteRaw(id interface{}) *pluginStorerDeleteCall {
	return _c.Parent.OnDeleteRaw(id)
}

func (_c *pluginStorerCreateCall) OnGetRaw(id interface{}) *pluginStorerGetCall {
	return _c.Parent.OnGetRaw(id)
}

func (_c *pluginStorerCreateCall) OnGetByNameRaw(bParam interface{}, cParam interface{}, dParam interface{}) *pluginStorerGetByNameCall {
	return _c.Parent.OnGetByNameRaw(bParam, cParam, dParam)
}

func (_c *pluginStorerCreateCall) OnGetHashByNameRaw(module interface{}, version interface{}) *pluginStorerGetHashByNameCall {
	return _c.Parent.OnGetHashByNameRaw(module, version)
}

func (_c *pluginStorerCreateCall) OnListRaw(bParam interface{}) *pluginStorerListCall {
	return _c.Parent.OnListRaw(bParam)
}

func (_c *pluginStorerCreateCall) OnSearchByNameRaw(bParam interface{}, cParam interface{}) *pluginStorerSearchByNameCall {
	return _c.Parent.OnSearchByNameRaw(bParam, cParam)
}

func (_c *pluginStorerCreateCall) OnUpdateRaw(bParam interface{}, cParam interface{}) *pluginStorerUpdateCall {
	return _c.Parent.OnUpdateRaw(bParam, cParam)
}

func (_m *pluginStorerMock) CreateHash(_ context.Context, module string, version string, hash string) (db.PluginHash, error) {
	_ret := _m.Called(module, version, hash)

	if _rf, ok := _ret.Get(0).(func(string, string, string) (db.PluginHash, error)); ok {
		return _rf(module, version, hash)
	}

	_ra0, _ := _ret.Get(0).(db.PluginHash)
	_rb1 := _ret.Error(1)

	return _ra0, _rb1
}

func (_m *pluginStorerMock) OnCreateHash(module string, version string, hash string) *pluginStorerCreateHashCall {
	return &pluginStorerCreateHashCall{Call: _m.Mock.On("CreateHash", module, version, hash), Parent: _m}
}

func (_m *pluginStorerMock) OnCreateHashRaw(module interface{}, version interface{}, hash interface{}) *pluginStorerCreateHashCall {
	return &pluginStorerCreateHashCall{Call: _m.Mock.On("CreateHash", module, version, hash), Parent: _m}
}

type pluginStorerCreateHashCall struct {
	*mock.Call
	Parent *pluginStorerMock
}

func (_c *pluginStorerCreateHashCall) Panic(msg string) *pluginStorerCreateHashCall {
	_c.Call = _c.Call.Panic(msg)
	return _c
}

func (_c *pluginStorerCreateHashCall) Once() *pluginStorerCreateHashCall {
	_c.Call = _c.Call.Once()
	return _c
}

func (_c *pluginStorerCreateHashCall) Twice() *pluginStorerCreateHashCall {
	_c.Call = _c.Call.Twice()
	return _c
}

func (_c *pluginStorerCreateHashCall) Times(i int) *pluginStorerCreateHashCall {
	_c.Call = _c.Call.Times(i)
	return _c
}

func (_c *pluginStorerCreateHashCall) WaitUntil(w <-chan time.Time) *pluginStorerCreateHashCall {
	_c.Call = _c.Call.WaitUntil(w)
	return _c
}

func (_c *pluginStorerCreateHashCall) After(d time.Duration) *pluginStorerCreateHashCall {
	_c.Call = _c.Call.After(d)
	return _c
}

func (_c *pluginStorerCreateHashCall) Run(fn func(args mock.Arguments)) *pluginStorerCreateHashCall {
	_c.Call = _c.Call.Run(fn)
	return _c
}

func (_c *pluginStorerCreateHashCall) Maybe() *pluginStorerCreateHashCall {
	_c.Call = _c.Call.Maybe()
	return _c
}

func (_c *pluginStorerCreateHashCall) TypedReturns(a db.PluginHash, b error) *pluginStorerCreateHashCall {
	_c.Call = _c.Return(a, b)
	return _c
}

func (_c *pluginStorerCreateHashCall) ReturnsFn(fn func(string, string, string) (db.PluginHash, error)) *pluginStorerCreateHashCall {
	_c.Call = _c.Return(fn)
	return _c
}

func (_c *pluginStorerCreateHashCall) TypedRun(fn func(string, string, string)) *pluginStorerCreateHashCall {
	_c.Call = _c.Call.Run(func(args mock.Arguments) {
		_module := args.String(0)
		_version := args.String(1)
		_hash := args.String(2)
		fn(_module, _version, _hash)
	})
	return _c
}

func (_c *pluginStorerCreateHashCall) OnCreate(bParam db.Plugin) *pluginStorerCreateCall {
	return _c.Parent.OnCreate(bParam)
}

func (_c *pluginStorerCreateHashCall) OnCreateHash(module string, version string, hash string) *pluginStorerCreateHashCall {
	return _c.Parent.OnCreateHash(module, version, hash)
}

func (_c *pluginStorerCreateHashCall) OnDelete(id string) *pluginStorerDeleteCall {
	return _c.Parent.OnDelete(id)
}

func (_c *pluginStorerCreateHashCall) OnGet(id string) *pluginStorerGetCall {
	return _c.Parent.OnGet(id)
}

func (_c *pluginStorerCreateHashCall) OnGetByName(bParam string, cParam bool, dParam bool) *pluginStorerGetByNameCall {
	return _c.Parent.OnGetByName(bParam, cParam, dParam)
}

func (_c *pluginStorerCreateHashCall) OnGetHashByName(module string, version string) *pluginStorerGetHashByNameCall {
	return _c.Parent.OnGetHashByName(module, version)
}

func (_c *pluginStorerCreateHashCall) OnList(bParam db.Pagination) *pluginStorerListCall {
	return _c.Parent.OnList(bParam)
}

func (_c *pluginStorerCreateHashCall) OnSearchByName(bParam string, cParam db.Pagination) *pluginStorerSearchByNameCall {
	return _c.Parent.OnSearchByName(bParam, cParam)
}

func (_c *pluginStorerCreateHashCall) OnUpdate(bParam string, cParam db.Plugin) *pluginStorerUpdateCall {
	return _c.Parent.OnUpdate(bParam, cParam)
}

func (_c *pluginStorerCreateHashCall) OnCreateRaw(bParam interface{}) *pluginStorerCreateCall {
	return _c.Parent.OnCreateRaw(bParam)
}

func (_c *pluginStorerCreateHashCall) OnCreateHashRaw(module interface{}, version interface{}, hash interface{}) *pluginStorerCreateHashCall {
	return _c.Parent.OnCreateHashRaw(module, version, hash)
}

func (_c *pluginStorerCreateHashCall) OnDeleteRaw(id interface{}) *pluginStorerDeleteCall {
	return _c.Parent.OnDeleteRaw(id)
}

func (_c *pluginStorerCreateHashCall) OnGetRaw(id interface{}) *pluginStorerGetCall {
	return _c.Parent.OnGetRaw(id)
}

func (_c *pluginStorerCreateHashCall) OnGetByNameRaw(bParam interface{}, cParam interface{}, dParam interface{}) *pluginStorerGetByNameCall {
	return _c.Parent.OnGetByNameRaw(bParam, cParam, dParam)
}

func (_c *pluginStorerCreateHashCall) OnGetHashByNameRaw(module interface{}, version interface{}) *pluginStorerGetHashByNameCall {
	return _c.Parent.OnGetHashByNameRaw(module, version)
}

func (_c *pluginStorerCreateHashCall) OnListRaw(bParam interface{}) *pluginStorerListCall {
	return _c.Parent.OnListRaw(bParam)
}

func (_c *pluginStorerCreateHashCall) OnSearchByNameRaw(bParam interface{}, cParam interface{}) *pluginStorerSearchByNameCall {
	return _c.Parent.OnSearchByNameRaw(bParam, cParam)
}

func (_c *pluginStorerCreateHashCall) OnUpdateRaw(bParam interface{}, cParam interface{}) *pluginStorerUpdateCall {
	return _c.Parent.OnUpdateRaw(bParam, cParam)
}

func (_m *pluginStorerMock) Delete(_ context.Context, id string) error {
	_ret := _m.Called(id)

	if _rf, ok := _ret.Get(0).(func(string) error); ok {
		return _rf(id)
	}

	_ra0 := _ret.Error(0)

	return _ra0
}

func (_m *pluginStorerMock) OnDelete(id string) *pluginStorerDeleteCall {
	return &pluginStorerDeleteCall{Call: _m.Mock.On("Delete", id), Parent: _m}
}

func (_m *pluginStorerMock) OnDeleteRaw(id interface{}) *pluginStorerDeleteCall {
	return &pluginStorerDeleteCall{Call: _m.Mock.On("Delete", id), Parent: _m}
}

type pluginStorerDeleteCall struct {
	*mock.Call
	Parent *pluginStorerMock
}

func (_c *pluginStorerDeleteCall) Panic(msg string) *pluginStorerDeleteCall {
	_c.Call = _c.Call.Panic(msg)
	return _c
}

func (_c *pluginStorerDeleteCall) Once() *pluginStorerDeleteCall {
	_c.Call = _c.Call.Once()
	return _c
}

func (_c *pluginStorerDeleteCall) Twice() *pluginStorerDeleteCall {
	_c.Call = _c.Call.Twice()
	return _c
}

func (_c *pluginStorerDeleteCall) Times(i int) *pluginStorerDeleteCall {
	_c.Call = _c.Call.Times(i)
	return _c
}

func (_c *pluginStorerDeleteCall) WaitUntil(w <-chan time.Time) *pluginStorerDeleteCall {
	_c.Call = _c.Call.WaitUntil(w)
	return _c
}

func (_c *pluginStorerDeleteCall) After(d time.Duration) *pluginStorerDeleteCall {
	_c.Call = _c.Call.After(d)
	return _c
}

func (_c *pluginStorerDeleteCall) Run(fn func(args mock.Arguments)) *pluginStorerDeleteCall {
	_c.Call = _c.Call.Run(fn)
	return _c
}

func (_c *pluginStorerDeleteCall) Maybe() *pluginStorerDeleteCall {
	_c.Call = _c.Call.Maybe()
	return _c
}

func (_c *pluginStorerDeleteCall) TypedReturns(a error) *pluginStorerDeleteCall {
	_c.Call = _c.Return(a)
	return _c
}

func (_c *pluginStorerDeleteCall) ReturnsFn(fn func(string) error) *pluginStorerDeleteCall {
	_c.Call = _c.Return(fn)
	return _c
}

func (_c *pluginStorerDeleteCall) TypedRun(fn func(string)) *pluginStorerDeleteCall {
	_c.Call = _c.Call.Run(func(args mock.Arguments) {
		_id := args.String(0)
		fn(_id)
	})
	return _c
}

func (_c *pluginStorerDeleteCall) OnCreate(bParam db.Plugin) *pluginStorerCreateCall {
	return _c.Parent.OnCreate(bParam)
}

func (_c *pluginStorerDeleteCall) OnCreateHash(module string, version string, hash string) *pluginStorerCreateHashCall {
	return _c.Parent.OnCreateHash(module, version, hash)
}

func (_c *pluginStorerDeleteCall) OnDelete(id string) *pluginStorerDeleteCall {
	return _c.Parent.OnDelete(id)
}

func (_c *pluginStorerDeleteCall) OnGet(id string) *pluginStorerGetCall {
	return _c.Parent.OnGet(id)
}

func (_c *pluginStorerDeleteCall) OnGetByName(bParam string, cParam bool, dParam bool) *pluginStorerGetByNameCall {
	return _c.Parent.OnGetByName(bParam, cParam, dParam)
}

func (_c *pluginStorerDeleteCall) OnGetHashByName(module string, version string) *pluginStorerGetHashByNameCall {
	return _c.Parent.OnGetHashByName(module, version)
}

func (_c *pluginStorerDeleteCall) OnList(bParam db.Pagination) *pluginStorerListCall {
	return _c.Parent.OnList(bParam)
}

func (_c *pluginStorerDeleteCall) OnSearchByName(bParam string, cParam db.Pagination) *pluginStorerSearchByNameCall {
	return _c.Parent.OnSearchByName(bParam, cParam)
}

func (_c *pluginStorerDeleteCall) OnUpdate(bParam string, cParam db.Plugin) *pluginStorerUpdateCall {
	return _c.Parent.OnUpdate(bParam, cParam)
}

func (_c *pluginStorerDeleteCall) OnCreateRaw(bParam interface{}) *pluginStorerCreateCall {
	return _c.Parent.OnCreateRaw(bParam)
}

func (_c *pluginStorerDeleteCall) OnCreateHashRaw(module interface{}, version interface{}, hash interface{}) *pluginStorerCreateHashCall {
	return _c.Parent.OnCreateHashRaw(module, version, hash)
}

func (_c *pluginStorerDeleteCall) OnDeleteRaw(id interface{}) *pluginStorerDeleteCall {
	return _c.Parent.OnDeleteRaw(id)
}

func (_c *pluginStorerDeleteCall) OnGetRaw(id interface{}) *pluginStorerGetCall {
	return _c.Parent.OnGetRaw(id)
}

func (_c *pluginStorerDeleteCall) OnGetByNameRaw(bParam interface{}, cParam interface{}, dParam interface{}) *pluginStorerGetByNameCall {
	return _c.Parent.OnGetByNameRaw(bParam, cParam, dParam)
}

func (_c *pluginStorerDeleteCall) OnGetHashByNameRaw(module interface{}, version interface{}) *pluginStorerGetHashByNameCall {
	return _c.Parent.OnGetHashByNameRaw(module, version)
}

func (_c *pluginStorerDeleteCall) OnListRaw(bParam interface{}) *pluginStorerListCall {
	return _c.Parent.OnListRaw(bParam)
}

func (_c *pluginStorerDeleteCall) OnSearchByNameRaw(bParam interface{}, cParam interface{}) *pluginStorerSearchByNameCall {
	return _c.Parent.OnSearchByNameRaw(bParam, cParam)
}

func (_c *pluginStorerDeleteCall) OnUpdateRaw(bParam interface{}, cParam interface{}) *pluginStorerUpdateCall {
	return _c.Parent.OnUpdateRaw(bParam, cParam)
}

func (_m *pluginStorerMock) Get(_ context.Context, id string) (db.Plugin, error) {
	_ret := _m.Called(id)

	if _rf, ok := _ret.Get(0).(func(string) (db.Plugin, error)); ok {
		return _rf(id)
	}

	_ra0, _ := _ret.Get(0).(db.Plugin)
	_rb1 := _ret.Error(1)

	return _ra0, _rb1
}

func (_m *pluginStorerMock) OnGet(id string) *pluginStorerGetCall {
	return &pluginStorerGetCall{Call: _m.Mock.On("Get", id), Parent: _m}
}

func (_m *pluginStorerMock) OnGetRaw(id interface{}) *pluginStorerGetCall {
	return &pluginStorerGetCall{Call: _m.Mock.On("Get", id), Parent: _m}
}

type pluginStorerGetCall struct {
	*mock.Call
	Parent *pluginStorerMock
}

func (_c *pluginStorerGetCall) Panic(msg string) *pluginStorerGetCall {
	_c.Call = _c.Call.Panic(msg)
	return _c
}

func (_c *pluginStorerGetCall) Once() *pluginStorerGetCall {
	_c.Call = _c.Call.Once()
	return _c
}

func (_c *pluginStorerGetCall) Twice() *pluginStorerGetCall {
	_c.Call = _c.Call.Twice()
	return _c
}

func (_c *pluginStorerGetCall) Times(i int) *pluginStorerGetCall {
	_c.Call = _c.Call.Times(i)
	return _c
}

func (_c *pluginStorerGetCall) WaitUntil(w <-chan time.Time) *pluginStorerGetCall {
	_c.Call = _c.Call.WaitUntil(w)
	return _c
}

func (_c *pluginStorerGetCall) After(d time.Duration) *pluginStorerGetCall {
	_c.Call = _c.Call.After(d)
	return _c
}

func (_c *pluginStorerGetCall) Run(fn func(args mock.Arguments)) *pluginStorerGetCall {
	_c.Call = _c.Call.Run(fn)
	return _c
}

func (_c *pluginStorerGetCall) Maybe() *pluginStorerGetCall {
	_c.Call = _c.Call.Maybe()
	return _c
}

func (_c *pluginStorerGetCall) TypedReturns(a db.Plugin, b error) *pluginStorerGetCall {
	_c.Call = _c.Return(a, b)
	return _c
}

func (_c *pluginStorerGetCall) ReturnsFn(fn func(string) (db.Plugin, error)) *pluginStorerGetCall {
	_c.Call = _c.Return(fn)
	return _c
}

func (_c *pluginStorerGetCall) TypedRun(fn func(string)) *pluginStorerGetCall {
	_c.Call = _c.Call.Run(func(args mock.Arguments) {
		_id := args.String(0)
		fn(_id)
	})
	return _c
}

func (_c *pluginStorerGetCall) OnCreate(bParam db.Plugin) *pluginStorerCreateCall {
	return _c.Parent.OnCreate(bParam)
}

func (_c *pluginStorerGetCall) OnCreateHash(module string, version string, hash string) *pluginStorerCreateHashCall {
	return _c.Parent.OnCreateHash(module, version, hash)
}

func (_c *pluginStorerGetCall) OnDelete(id string) *pluginStorerDeleteCall {
	return _c.Parent.OnDelete(id)
}

func (_c *pluginStorerGetCall) OnGet(id string) *pluginStorerGetCall {
	return _c.Parent.OnGet(id)
}

func (_c *pluginStorerGetCall) OnGetByName(bParam string, cParam bool, dParam bool) *pluginStorerGetByNameCall {
	return _c.Parent.OnGetByName(bParam, cParam, dParam)
}

func (_c *pluginStorerGetCall) OnGetHashByName(module string, version string) *pluginStorerGetHashByNameCall {
	return _c.Parent.OnGetHashByName(module, version)
}

func (_c *pluginStorerGetCall) OnList(bParam db.Pagination) *pluginStorerListCall {
	return _c.Parent.OnList(bParam)
}

func (_c *pluginStorerGetCall) OnSearchByName(bParam string, cParam db.Pagination) *pluginStorerSearchByNameCall {
	return _c.Parent.OnSearchByName(bParam, cParam)
}

func (_c *pluginStorerGetCall) OnUpdate(bParam string, cParam db.Plugin) *pluginStorerUpdateCall {
	return _c.Parent.OnUpdate(bParam, cParam)
}

func (_c *pluginStorerGetCall) OnCreateRaw(bParam interface{}) *pluginStorerCreateCall {
	return _c.Parent.OnCreateRaw(bParam)
}

func (_c *pluginStorerGetCall) OnCreateHashRaw(module interface{}, version interface{}, hash interface{}) *pluginStorerCreateHashCall {
	return _c.Parent.OnCreateHashRaw(module, version, hash)
}

func (_c *pluginStorerGetCall) OnDeleteRaw(id interface{}) *pluginStorerDeleteCall {
	return _c.Parent.OnDeleteRaw(id)
}

func (_c *pluginStorerGetCall) OnGetRaw(id interface{}) *pluginStorerGetCall {
	return _c.Parent.OnGetRaw(id)
}

func (_c *pluginStorerGetCall) OnGetByNameRaw(bParam interface{}, cParam interface{}, dParam interface{}) *pluginStorerGetByNameCall {
	return _c.Parent.OnGetByNameRaw(bParam, cParam, dParam)
}

func (_c *pluginStorerGetCall) OnGetHashByNameRaw(module interface{}, version interface{}) *pluginStorerGetHashByNameCall {
	return _c.Parent.OnGetHashByNameRaw(module, version)
}

func (_c *pluginStorerGetCall) OnListRaw(bParam interface{}) *pluginStorerListCall {
	return _c.Parent.OnListRaw(bParam)
}

func (_c *pluginStorerGetCall) OnSearchByNameRaw(bParam interface{}, cParam interface{}) *pluginStorerSearchByNameCall {
	return _c.Parent.OnSearchByNameRaw(bParam, cParam)
}

func (_c *pluginStorerGetCall) OnUpdateRaw(bParam interface{}, cParam interface{}) *pluginStorerUpdateCall {
	return _c.Parent.OnUpdateRaw(bParam, cParam)
}

func (_m *pluginStorerMock) GetByName(_ context.Context, bParam string, cParam bool, dParam bool) (db.Plugin, error) {
	_ret := _m.Called(bParam, cParam, dParam)

	if _rf, ok := _ret.Get(0).(func(string, bool, bool) (db.Plugin, error)); ok {
		return _rf(bParam, cParam, dParam)
	}

	_ra0, _ := _ret.Get(0).(db.Plugin)
	_rb1 := _ret.Error(1)

	return _ra0, _rb1
}

func (_m *pluginStorerMock) OnGetByName(bParam string, cParam bool, dParam bool) *pluginStorerGetByNameCall {
	return &pluginStorerGetByNameCall{Call: _m.Mock.On("GetByName", bParam, cParam, dParam), Parent: _m}
}

func (_m *pluginStorerMock) OnGetByNameRaw(bParam interface{}, cParam interface{}, dParam interface{}) *pluginStorerGetByNameCall {
	return &pluginStorerGetByNameCall{Call: _m.Mock.On("GetByName", bParam, cParam, dParam), Parent: _m}
}

type pluginStorerGetByNameCall struct {
	*mock.Call
	Parent *pluginStorerMock
}

func (_c *pluginStorerGetByNameCall) Panic(msg string) *pluginStorerGetByNameCall {
	_c.Call = _c.Call.Panic(msg)
	return _c
}

func (_c *pluginStorerGetByNameCall) Once() *pluginStorerGetByNameCall {
	_c.Call = _c.Call.Once()
	return _c
}

func (_c *pluginStorerGetByNameCall) Twice() *pluginStorerGetByNameCall {
	_c.Call = _c.Call.Twice()
	return _c
}

func (_c *pluginStorerGetByNameCall) Times(i int) *pluginStorerGetByNameCall {
	_c.Call = _c.Call.Times(i)
	return _c
}

func (_c *pluginStorerGetByNameCall) WaitUntil(w <-chan time.Time) *pluginStorerGetByNameCall {
	_c.Call = _c.Call.WaitUntil(w)
	return _c
}

func (_c *pluginStorerGetByNameCall) After(d time.Duration) *pluginStorerGetByNameCall {
	_c.Call = _c.Call.After(d)
	return _c
}

func (_c *pluginStorerGetByNameCall) Run(fn func(args mock.Arguments)) *pluginStorerGetByNameCall {
	_c.Call = _c.Call.Run(fn)
	return _c
}

func (_c *pluginStorerGetByNameCall) Maybe() *pluginStorerGetByNameCall {
	_c.Call = _c.Call.Maybe()
	return _c
}

func (_c *pluginStorerGetByNameCall) TypedReturns(a db.Plugin, b error) *pluginStorerGetByNameCall {
	_c.Call = _c.Return(a, b)
	return _c
}

func (_c *pluginStorerGetByNameCall) ReturnsFn(fn func(string, bool, bool) (db.Plugin, error)) *pluginStorerGetByNameCall {
	_c.Call = _c.Return(fn)
	return _c
}

func (_c *pluginStorerGetByNameCall) TypedRun(fn func(string, bool, bool)) *pluginStorerGetByNameCall {
	_c.Call = _c.Call.Run(func(args mock.Arguments) {
		_bParam := args.String(0)
		_cParam := args.Bool(1)
		_dParam := args.Bool(2)
		fn(_bParam, _cParam, _dParam)
	})
	return _c
}

func (_c *pluginStorerGetByNameCall) OnCreate(bParam db.Plugin) *pluginStorerCreateCall {
	return _c.Parent.OnCreate(bParam)
}

func (_c *pluginStorerGetByNameCall) OnCreateHash(module string, version string, hash string) *pluginStorerCreateHashCall {
	return _c.Parent.OnCreateHash(module, version, hash)
}

func (_c *pluginStorerGetByNameCall) OnDelete(id string) *pluginStorerDeleteCall {
	return _c.Parent.OnDelete(id)
}

func (_c *pluginStorerGetByNameCall) OnGet(id string) *pluginStorerGetCall {
	return _c.Parent.OnGet(id)
}

func (_c *pluginStorerGetByNameCall) OnGetByName(bParam string, cParam bool, dParam bool) *pluginStorerGetByNameCall {
	return _c.Parent.OnGetByName(bParam, cParam, dParam)
}

func (_c *pluginStorerGetByNameCall) OnGetHashByName(module string, version string) *pluginStorerGetHashByNameCall {
	return _c.Parent.OnGetHashByName(module, version)
}

func (_c *pluginStorerGetByNameCall) OnList(bParam db.Pagination) *pluginStorerListCall {
	return _c.Parent.OnList(bParam)
}

func (_c *pluginStorerGetByNameCall) OnSearchByName(bParam string, cParam db.Pagination) *pluginStorerSearchByNameCall {
	return _c.Parent.OnSearchByName(bParam, cParam)
}

func (_c *pluginStorerGetByNameCall) OnUpdate(bParam string, cParam db.Plugin) *pluginStorerUpdateCall {
	return _c.Parent.OnUpdate(bParam, cParam)
}

func (_c *pluginStorerGetByNameCall) OnCreateRaw(bParam interface{}) *pluginStorerCreateCall {
	return _c.Parent.OnCreateRaw(bParam)
}

func (_c *pluginStorerGetByNameCall) OnCreateHashRaw(module interface{}, version interface{}, hash interface{}) *pluginStorerCreateHashCall {
	return _c.Parent.OnCreateHashRaw(module, version, hash)
}

func (_c *pluginStorerGetByNameCall) OnDeleteRaw(id interface{}) *pluginStorerDeleteCall {
	return _c.Parent.OnDeleteRaw(id)
}

func (_c *pluginStorerGetByNameCall) OnGetRaw(id interface{}) *pluginStorerGetCall {
	return _c.Parent.OnGetRaw(id)
}

func (_c *pluginStorerGetByNameCall) OnGetByNameRaw(bParam interface{}, cParam interface{}, dParam interface{}) *pluginStorerGetByNameCall {
	return _c.Parent.OnGetByNameRaw(bParam, cParam, dParam)
}

func (_c *pluginStorerGetByNameCall) OnGetHashByNameRaw(module interface{}, version interface{}) *pluginStorerGetHashByNameCall {
	return _c.Parent.OnGetHashByNameRaw(module, version)
}

func (_c *pluginStorerGetByNameCall) OnListRaw(bParam interface{}) *pluginStorerListCall {
	return _c.Parent.OnListRaw(bParam)
}

func (_c *pluginStorerGetByNameCall) OnSearchByNameRaw(bParam interface{}, cParam interface{}) *pluginStorerSearchByNameCall {
	return _c.Parent.OnSearchByNameRaw(bParam, cParam)
}

func (_c *pluginStorerGetByNameCall) OnUpdateRaw(bParam interface{}, cParam interface{}) *pluginStorerUpdateCall {
	return _c.Parent.OnUpdateRaw(bParam, cParam)
}

func (_m *pluginStorerMock) GetHashByName(_ context.Context, module string, version string) (db.PluginHash, error) {
	_ret := _m.Called(module, version)

	if _rf, ok := _ret.Get(0).(func(string, string) (db.PluginHash, error)); ok {
		return _rf(module, version)
	}

	_ra0, _ := _ret.Get(0).(db.PluginHash)
	_rb1 := _ret.Error(1)

	return _ra0, _rb1
}

func (_m *pluginStorerMock) OnGetHashByName(module string, version string) *pluginStorerGetHashByNameCall {
	return &pluginStorerGetHashByNameCall{Call: _m.Mock.On("GetHashByName", module, version), Parent: _m}
}

func (_m *pluginStorerMock) OnGetHashByNameRaw(module interface{}, version interface{}) *pluginStorerGetHashByNameCall {
	return &pluginStorerGetHashByNameCall{Call: _m.Mock.On("GetHashByName", module, version), Parent: _m}
}

type pluginStorerGetHashByNameCall struct {
	*mock.Call
	Parent *pluginStorerMock
}

func (_c *pluginStorerGetHashByNameCall) Panic(msg string) *pluginStorerGetHashByNameCall {
	_c.Call = _c.Call.Panic(msg)
	return _c
}

func (_c *pluginStorerGetHashByNameCall) Once() *pluginStorerGetHashByNameCall {
	_c.Call = _c.Call.Once()
	return _c
}

func (_c *pluginStorerGetHashByNameCall) Twice() *pluginStorerGetHashByNameCall {
	_c.Call = _c.Call.Twice()
	return _c
}

func (_c *pluginStorerGetHashByNameCall) Times(i int) *pluginStorerGetHashByNameCall {
	_c.Call = _c.Call.Times(i)
	return _c
}

func (_c *pluginStorerGetHashByNameCall) WaitUntil(w <-chan time.Time) *pluginStorerGetHashByNameCall {
	_c.Call = _c.Call.WaitUntil(w)
	return _c
}

func (_c *pluginStorerGetHashByNameCall) After(d time.Duration) *pluginStorerGetHashByNameCall {
	_c.Call = _c.Call.After(d)
	return _c
}

func (_c *pluginStorerGetHashByNameCall) Run(fn func(args mock.Arguments)) *pluginStorerGetHashByNameCall {
	_c.Call = _c.Call.Run(fn)
	return _c
}

func (_c *pluginStorerGetHashByNameCall) Maybe() *pluginStorerGetHashByNameCall {
	_c.Call = _c.Call.Maybe()
	return _c
}

func (_c *pluginStorerGetHashByNameCall) TypedReturns(a db.PluginHash, b error) *pluginStorerGetHashByNameCall {
	_c.Call = _c.Return(a, b)
	return _c
}

func (_c *pluginStorerGetHashByNameCall) ReturnsFn(fn func(string, string) (db.PluginHash, error)) *pluginStorerGetHashByNameCall {
	_c.Call = _c.Return(fn)
	return _c
}

func (_c *pluginStorerGetHashByNameCall) TypedRun(fn func(string, string)) *pluginStorerGetHashByNameCall {
	_c.Call = _c.Call.Run(func(args mock.Arguments) {
		_module := args.String(0)
		_version := args.String(1)
		fn(_module, _version)
	})
	return _c
}

func (_c *pluginStorerGetHashByNameCall) OnCreate(bParam db.Plugin) *pluginStorerCreateCall {
	return _c.Parent.OnCreate(bParam)
}

func (_c *pluginStorerGetHashByNameCall) OnCreateHash(module string, version string, hash string) *pluginStorerCreateHashCall {
	return _c.Parent.OnCreateHash(module, version, hash)
}

func (_c *pluginStorerGetHashByNameCall) OnDelete(id string) *pluginStorerDeleteCall {
	return _c.Parent.OnDelete(id)
}

func (_c *pluginStorerGetHashByNameCall) OnGet(id string) *pluginStorerGetCall {
	return _c.Parent.OnGet(id)
}

func (_c *pluginStorerGetHashByNameCall) OnGetByName(bParam string, cParam bool, dParam bool) *pluginStorerGetByNameCall {
	return _c.Parent.OnGetByName(bParam, cParam, dParam)
}

func (_c *pluginStorerGetHashByNameCall) OnGetHashByName(module string, version string) *pluginStorerGetHashByNameCall {
	return _c.Parent.OnGetHashByName(module, version)
}

func (_c *pluginStorerGetHashByNameCall) OnList(bParam db.Pagination) *pluginStorerListCall {
	return _c.Parent.OnList(bParam)
}

func (_c *pluginStorerGetHashByNameCall) OnSearchByName(bParam string, cParam db.Pagination) *pluginStorerSearchByNameCall {
	return _c.Parent.OnSearchByName(bParam, cParam)
}

func (_c *pluginStorerGetHashByNameCall) OnUpdate(bParam string, cParam db.Plugin) *pluginStorerUpdateCall {
	return _c.Parent.OnUpdate(bParam, cParam)
}

func (_c *pluginStorerGetHashByNameCall) OnCreateRaw(bParam interface{}) *pluginStorerCreateCall {
	return _c.Parent.OnCreateRaw(bParam)
}

func (_c *pluginStorerGetHashByNameCall) OnCreateHashRaw(module interface{}, version interface{}, hash interface{}) *pluginStorerCreateHashCall {
	return _c.Parent.OnCreateHashRaw(module, version, hash)
}

func (_c *pluginStorerGetHashByNameCall) OnDeleteRaw(id interface{}) *pluginStorerDeleteCall {
	return _c.Parent.OnDeleteRaw(id)
}

func (_c *pluginStorerGetHashByNameCall) OnGetRaw(id interface{}) *pluginStorerGetCall {
	return _c.Parent.OnGetRaw(id)
}

func (_c *pluginStorerGetHashByNameCall) OnGetByNameRaw(bParam interface{}, cParam interface{}, dParam interface{}) *pluginStorerGetByNameCall {
	return _c.Parent.OnGetByNameRaw(bParam, cParam, dParam)
}

func (_c *pluginStorerGetHashByNameCall) OnGetHashByNameRaw(module interface{}, version interface{}) *pluginStorerGetHashByNameCall {
	return _c.Parent.OnGetHashByNameRaw(module, version)
}

func (_c *pluginStorerGetHashByNameCall) OnListRaw(bParam interface{}) *pluginStorerListCall {
	return _c.Parent.OnListRaw(bParam)
}

func (_c *pluginStorerGetHashByNameCall) OnSearchByNameRaw(bParam interface{}, cParam interface{}) *pluginStorerSearchByNameCall {
	return _c.Parent.OnSearchByNameRaw(bParam, cParam)
}

func (_c *pluginStorerGetHashByNameCall) OnUpdateRaw(bParam interface{}, cParam interface{}) *pluginStorerUpdateCall {
	return _c.Parent.OnUpdateRaw(bParam, cParam)
}

func (_m *pluginStorerMock) List(_ context.Context, bParam db.Pagination) ([]db.Plugin, string, error) {
	_ret := _m.Called(bParam)

	if _rf, ok := _ret.Get(0).(func(db.Pagination) ([]db.Plugin, string, error)); ok {
		return _rf(bParam)
	}

	_ra0, _ := _ret.Get(0).([]db.Plugin)
	_rb1 := _ret.String(1)
	_rc2 := _ret.Error(2)

	return _ra0, _rb1, _rc2
}

func (_m *pluginStorerMock) OnList(bParam db.Pagination) *pluginStorerListCall {
	return &pluginStorerListCall{Call: _m.Mock.On("List", bParam), Parent: _m}
}

func (_m *pluginStorerMock) OnListRaw(bParam interface{}) *pluginStorerListCall {
	return &pluginStorerListCall{Call: _m.Mock.On("List", bParam), Parent: _m}
}

type pluginStorerListCall struct {
	*mock.Call
	Parent *pluginStorerMock
}

func (_c *pluginStorerListCall) Panic(msg string) *pluginStorerListCall {
	_c.Call = _c.Call.Panic(msg)
	return _c
}

func (_c *pluginStorerListCall) Once() *pluginStorerListCall {
	_c.Call = _c.Call.Once()
	return _c
}

func (_c *pluginStorerListCall) Twice() *pluginStorerListCall {
	_c.Call = _c.Call.Twice()
	return _c
}

func (_c *pluginStorerListCall) Times(i int) *pluginStorerListCall {
	_c.Call = _c.Call.Times(i)
	return _c
}

func (_c *pluginStorerListCall) WaitUntil(w <-chan time.Time) *pluginStorerListCall {
	_c.Call = _c.Call.WaitUntil(w)
	return _c
}

func (_c *pluginStorerListCall) After(d time.Duration) *pluginStorerListCall {
	_c.Call = _c.Call.After(d)
	return _c
}

func (_c *pluginStorerListCall) Run(fn func(args mock.Arguments)) *pluginStorerListCall {
	_c.Call = _c.Call.Run(fn)
	return _c
}

func (_c *pluginStorerListCall) Maybe() *pluginStorerListCall {
	_c.Call = _c.Call.Maybe()
	return _c
}

func (_c *pluginStorerListCall) TypedReturns(a []db.Plugin, b string, c error) *pluginStorerListCall {
	_c.Call = _c.Return(a, b, c)
	return _c
}

func (_c *pluginStorerListCall) ReturnsFn(fn func(db.Pagination) ([]db.Plugin, string, error)) *pluginStorerListCall {
	_c.Call = _c.Return(fn)
	return _c
}

func (_c *pluginStorerListCall) TypedRun(fn func(db.Pagination)) *pluginStorerListCall {
	_c.Call = _c.Call.Run(func(args mock.Arguments) {
		_bParam, _ := args.Get(0).(db.Pagination)
		fn(_bParam)
	})
	return _c
}

func (_c *pluginStorerListCall) OnCreate(bParam db.Plugin) *pluginStorerCreateCall {
	return _c.Parent.OnCreate(bParam)
}

func (_c *pluginStorerListCall) OnCreateHash(module string, version string, hash string) *pluginStorerCreateHashCall {
	return _c.Parent.OnCreateHash(module, version, hash)
}

func (_c *pluginStorerListCall) OnDelete(id string) *pluginStorerDeleteCall {
	return _c.Parent.OnDelete(id)
}

func (_c *pluginStorerListCall) OnGet(id string) *pluginStorerGetCall {
	return _c.Parent.OnGet(id)
}

func (_c *pluginStorerListCall) OnGetByName(bParam string, cParam bool, dParam bool) *pluginStorerGetByNameCall {
	return _c.Parent.OnGetByName(bParam, cParam, dParam)
}

func (_c *pluginStorerListCall) OnGetHashByName(module string, version string) *pluginStorerGetHashByNameCall {
	return _c.Parent.OnGetHashByName(module, version)
}

func (_c *pluginStorerListCall) OnList(bParam db.Pagination) *pluginStorerListCall {
	return _c.Parent.OnList(bParam)
}

func (_c *pluginStorerListCall) OnSearchByName(bParam string, cParam db.Pagination) *pluginStorerSearchByNameCall {
	return _c.Parent.OnSearchByName(bParam, cParam)
}

func (_c *pluginStorerListCall) OnUpdate(bParam string, cParam db.Plugin) *pluginStorerUpdateCall {
	return _c.Parent.OnUpdate(bParam, cParam)
}

func (_c *pluginStorerListCall) OnCreateRaw(bParam interface{}) *pluginStorerCreateCall {
	return _c.Parent.OnCreateRaw(bParam)
}

func (_c *pluginStorerListCall) OnCreateHashRaw(module interface{}, version interface{}, hash interface{}) *pluginStorerCreateHashCall {
	return _c.Parent.OnCreateHashRaw(module, version, hash)
}

func (_c *pluginStorerListCall) OnDeleteRaw(id interface{}) *pluginStorerDeleteCall {
	return _c.Parent.OnDeleteRaw(id)
}

func (_c *pluginStorerListCall) OnGetRaw(id interface{}) *pluginStorerGetCall {
	return _c.Parent.OnGetRaw(id)
}

func (_c *pluginStorerListCall) OnGetByNameRaw(bParam interface{}, cParam interface{}, dParam interface{}) *pluginStorerGetByNameCall {
	return _c.Parent.OnGetByNameRaw(bParam, cParam, dParam)
}

func (_c *pluginStorerListCall) OnGetHashByNameRaw(module interface{}, version interface{}) *pluginStorerGetHashByNameCall {
	return _c.Parent.OnGetHashByNameRaw(module, version)
}

func (_c *pluginStorerListCall) OnListRaw(bParam interface{}) *pluginStorerListCall {
	return _c.Parent.OnListRaw(bParam)
}

func (_c *pluginStorerListCall) OnSearchByNameRaw(bParam interface{}, cParam interface{}) *pluginStorerSearchByNameCall {
	return _c.Parent.OnSearchByNameRaw(bParam, cParam)
}

func (_c *pluginStorerListCall) OnUpdateRaw(bParam interface{}, cParam interface{}) *pluginStorerUpdateCall {
	return _c.Parent.OnUpdateRaw(bParam, cParam)
}

func (_m *pluginStorerMock) SearchByName(_ context.Context, bParam string, cParam db.Pagination) ([]db.Plugin, string, error) {
	_ret := _m.Called(bParam, cParam)

	if _rf, ok := _ret.Get(0).(func(string, db.Pagination) ([]db.Plugin, string, error)); ok {
		return _rf(bParam, cParam)
	}

	_ra0, _ := _ret.Get(0).([]db.Plugin)
	_rb1 := _ret.String(1)
	_rc2 := _ret.Error(2)

	return _ra0, _rb1, _rc2
}

func (_m *pluginStorerMock) OnSearchByName(bParam string, cParam db.Pagination) *pluginStorerSearchByNameCall {
	return &pluginStorerSearchByNameCall{Call: _m.Mock.On("SearchByName", bParam, cParam), Parent: _m}
}

func (_m *pluginStorerMock) OnSearchByNameRaw(bParam interface{}, cParam interface{}) *pluginStorerSearchByNameCall {
	return &pluginStorerSearchByNameCall{Call: _m.Mock.On("SearchByName", bParam, cParam), Parent: _m}
}

type pluginStorerSearchByNameCall struct {
	*mock.Call
	Parent *pluginStorerMock
}

func (_c *pluginStorerSearchByNameCall) Panic(msg string) *pluginStorerSearchByNameCall {
	_c.Call = _c.Call.Panic(msg)
	return _c
}

func (_c *pluginStorerSearchByNameCall) Once() *pluginStorerSearchByNameCall {
	_c.Call = _c.Call.Once()
	return _c
}

func (_c *pluginStorerSearchByNameCall) Twice() *pluginStorerSearchByNameCall {
	_c.Call = _c.Call.Twice()
	return _c
}

func (_c *pluginStorerSearchByNameCall) Times(i int) *pluginStorerSearchByNameCall {
	_c.Call = _c.Call.Times(i)
	return _c
}

func (_c *pluginStorerSearchByNameCall) WaitUntil(w <-chan time.Time) *pluginStorerSearchByNameCall {
	_c.Call = _c.Call.WaitUntil(w)
	return _c
}

func (_c *pluginStorerSearchByNameCall) After(d time.Duration) *pluginStorerSearchByNameCall {
	_c.Call = _c.Call.After(d)
	return _c
}

func (_c *pluginStorerSearchByNameCall) Run(fn func(args mock.Arguments)) *pluginStorerSearchByNameCall {
	_c.Call = _c.Call.Run(fn)
	return _c
}

func (_c *pluginStorerSearchByNameCall) Maybe() *pluginStorerSearchByNameCall {
	_c.Call = _c.Call.Maybe()
	return _c
}

func (_c *pluginStorerSearchByNameCall) TypedReturns(a []db.Plugin, b string, c error) *pluginStorerSearchByNameCall {
	_c.Call = _c.Return(a, b, c)
	return _c
}

func (_c *pluginStorerSearchByNameCall) ReturnsFn(fn func(string, db.Pagination) ([]db.Plugin, string, error)) *pluginStorerSearchByNameCall {
	_c.Call = _c.Return(fn)
	return _c
}

func (_c *pluginStorerSearchByNameCall) TypedRun(fn func(string, db.Pagination)) *pluginStorerSearchByNameCall {
	_c.Call = _c.Call.Run(func(args mock.Arguments) {
		_bParam := args.String(0)
		_cParam, _ := args.Get(1).(db.Pagination)
		fn(_bParam, _cParam)
	})
	return _c
}

func (_c *pluginStorerSearchByNameCall) OnCreate(bParam db.Plugin) *pluginStorerCreateCall {
	return _c.Parent.OnCreate(bParam)
}

func (_c *pluginStorerSearchByNameCall) OnCreateHash(module string, version string, hash string) *pluginStorerCreateHashCall {
	return _c.Parent.OnCreateHash(module, version, hash)
}

func (_c *pluginStorerSearchByNameCall) OnDelete(id string) *pluginStorerDeleteCall {
	return _c.Parent.OnDelete(id)
}

func (_c *pluginStorerSearchByNameCall) OnGet(id string) *pluginStorerGetCall {
	return _c.Parent.OnGet(id)
}

func (_c *pluginStorerSearchByNameCall) OnGetByName(bParam string, cParam bool, dParam bool) *pluginStorerGetByNameCall {
	return _c.Parent.OnGetByName(bParam, cParam, dParam)
}

func (_c *pluginStorerSearchByNameCall) OnGetHashByName(module string, version string) *pluginStorerGetHashByNameCall {
	return _c.Parent.OnGetHashByName(module, version)
}

func (_c *pluginStorerSearchByNameCall) OnList(bParam db.Pagination) *pluginStorerListCall {
	return _c.Parent.OnList(bParam)
}

func (_c *pluginStorerSearchByNameCall) OnSearchByName(bParam string, cParam db.Pagination) *pluginStorerSearchByNameCall {
	return _c.Parent.OnSearchByName(bParam, cParam)
}

func (_c *pluginStorerSearchByNameCall) OnUpdate(bParam string, cParam db.Plugin) *pluginStorerUpdateCall {
	return _c.Parent.OnUpdate(bParam, cParam)
}

func (_c *pluginStorerSearchByNameCall) OnCreateRaw(bParam interface{}) *pluginStorerCreateCall {
	return _c.Parent.OnCreateRaw(bParam)
}

func (_c *pluginStorerSearchByNameCall) OnCreateHashRaw(module interface{}, version interface{}, hash interface{}) *pluginStorerCreateHashCall {
	return _c.Parent.OnCreateHashRaw(module, version, hash)
}

func (_c *pluginStorerSearchByNameCall) OnDeleteRaw(id interface{}) *pluginStorerDeleteCall {
	return _c.Parent.OnDeleteRaw(id)
}

func (_c *pluginStorerSearchByNameCall) OnGetRaw(id interface{}) *pluginStorerGetCall {
	return _c.Parent.OnGetRaw(id)
}

func (_c *pluginStorerSearchByNameCall) OnGetByNameRaw(bParam interface{}, cParam interface{}, dParam interface{}) *pluginStorerGetByNameCall {
	return _c.Parent.OnGetByNameRaw(bParam, cParam, dParam)
}

func (_c *pluginStorerSearchByNameCall) OnGetHashByNameRaw(module interface{}, version interface{}) *pluginStorerGetHashByNameCall {
	return _c.Parent.OnGetHashByNameRaw(module, version)
}

func (_c *pluginStorerSearchByNameCall) OnListRaw(bParam interface{}) *pluginStorerListCall {
	return _c.Parent.OnListRaw(bParam)
}

func (_c *pluginStorerSearchByNameCall) OnSearchByNameRaw(bParam interface{}, cParam interface{}) *pluginStorerSearchByNameCall {
	return _c.Parent.OnSearchByNameRaw(bParam, cParam)
}

func (_c *pluginStorerSearchByNameCall) OnUpdateRaw(bParam interface{}, cParam interface{}) *pluginStorerUpdateCall {
	return _c.Parent.OnUpdateRaw(bParam, cParam)
}

func (_m *pluginStorerMock) Update(_ context.Context, bParam string, cParam db.Plugin) (db.Plugin, error) {
	_ret := _m.Called(bParam, cParam)

	if _rf, ok := _ret.Get(0).(func(string, db.Plugin) (db.Plugin, error)); ok {
		return _rf(bParam, cParam)
	}

	_ra0, _ := _ret.Get(0).(db.Plugin)
	_rb1 := _ret.Error(1)

	return _ra0, _rb1
}

func (_m *pluginStorerMock) OnUpdate(bParam string, cParam db.Plugin) *pluginStorerUpdateCall {
	return &pluginStorerUpdateCall{Call: _m.Mock.On("Update", bParam, cParam), Parent: _m}
}

func (_m *pluginStorerMock) OnUpdateRaw(bParam interface{}, cParam interface{}) *pluginStorerUpdateCall {
	return &pluginStorerUpdateCall{Call: _m.Mock.On("Update", bParam, cParam), Parent: _m}
}

type pluginStorerUpdateCall struct {
	*mock.Call
	Parent *pluginStorerMock
}

func (_c *pluginStorerUpdateCall) Panic(msg string) *pluginStorerUpdateCall {
	_c.Call = _c.Call.Panic(msg)
	return _c
}

func (_c *pluginStorerUpdateCall) Once() *pluginStorerUpdateCall {
	_c.Call = _c.Call.Once()
	return _c
}

func (_c *pluginStorerUpdateCall) Twice() *pluginStorerUpdateCall {
	_c.Call = _c.Call.Twice()
	return _c
}

func (_c *pluginStorerUpdateCall) Times(i int) *pluginStorerUpdateCall {
	_c.Call = _c.Call.Times(i)
	return _c
}

func (_c *pluginStorerUpdateCall) WaitUntil(w <-chan time.Time) *pluginStorerUpdateCall {
	_c.Call = _c.Call.WaitUntil(w)
	return _c
}

func (_c *pluginStorerUpdateCall) After(d time.Duration) *pluginStorerUpdateCall {
	_c.Call = _c.Call.After(d)
	return _c
}

func (_c *pluginStorerUpdateCall) Run(fn func(args mock.Arguments)) *pluginStorerUpdateCall {
	_c.Call = _c.Call.Run(fn)
	return _c
}

func (_c *pluginStorerUpdateCall) Maybe() *pluginStorerUpdateCall {
	_c.Call = _c.Call.Maybe()
	return _c
}

func (_c *pluginStorerUpdateCall) TypedReturns(a db.Plugin, b error) *pluginStorerUpdateCall {
	_c.Call = _c.Return(a, b)
	return _c
}

func (_c *pluginStorerUpdateCall) ReturnsFn(fn func(string, db.Plugin) (db.Plugin, error)) *pluginStorerUpdateCall {
	_c.Call = _c.Return(fn)
	return _c
}

func (_c *pluginStorerUpdateCall) TypedRun(fn func(string, db.Plugin)) *pluginStorerUpdateCall {
	_c.Call = _c.Call.Run(func(args mock.Arguments) {
		_bParam := args.String(0)
		_cParam, _ := args.Get(1).(db.Plugin)
		fn(_bParam, _cParam)
	})
	return _c
}

func (_c *pluginStorerUpdateCall) OnCreate(bParam db.Plugin) *pluginStorerCreateCall {
	return _c.Parent.OnCreate(bParam)
}

func (_c *pluginStorerUpdateCall) OnCreateHash(module string, version string, hash string) *pluginStorerCreateHashCall {
	return _c.Parent.OnCreateHash(module, version, hash)
}

func (_c *pluginStorerUpdateCall) OnDelete(id string) *pluginStorerDeleteCall {
	return _c.Parent.OnDelete(id)
}

func (_c *pluginStorerUpdateCall) OnGet(id string) *pluginStorerGetCall {
	return _c.Parent.OnGet(id)
}

func (_c *pluginStorerUpdateCall) OnGetByName(bParam string, cParam bool, dParam bool) *pluginStorerGetByNameCall {
	return _c.Parent.OnGetByName(bParam, cParam, dParam)
}

func (_c *pluginStorerUpdateCall) OnGetHashByName(module string, version string) *pluginStorerGetHashByNameCall {
	return _c.Parent.OnGetHashByName(module, version)
}

func (_c *pluginStorerUpdateCall) OnList(bParam db.Pagination) *pluginStorerListCall {
	return _c.Parent.OnList(bParam)
}

func (_c *pluginStorerUpdateCall) OnSearchByName(bParam string, cParam db.Pagination) *pluginStorerSearchByNameCall {
	return _c.Parent.OnSearchByName(bParam, cParam)
}

func (_c *pluginStorerUpdateCall) OnUpdate(bParam string, cParam db.Plugin) *pluginStorerUpdateCall {
	return _c.Parent.OnUpdate(bParam, cParam)
}

func (_c *pluginStorerUpdateCall) OnCreateRaw(bParam interface{}) *pluginStorerCreateCall {
	return _c.Parent.OnCreateRaw(bParam)
}

func (_c *pluginStorerUpdateCall) OnCreateHashRaw(module interface{}, version interface{}, hash interface{}) *pluginStorerCreateHashCall {
	return _c.Parent.OnCreateHashRaw(module, version, hash)
}

func (_c *pluginStorerUpdateCall) OnDeleteRaw(id interface{}) *pluginStorerDeleteCall {
	return _c.Parent.OnDeleteRaw(id)
}

func (_c *pluginStorerUpdateCall) OnGetRaw(id interface{}) *pluginStorerGetCall {
	return _c.Parent.OnGetRaw(id)
}

func (_c *pluginStorerUpdateCall) OnGetByNameRaw(bParam interface{}, cParam interface{}, dParam interface{}) *pluginStorerGetByNameCall {
	return _c.Parent.OnGetByNameRaw(bParam, cParam, dParam)
}

func (_c *pluginStorerUpdateCall) OnGetHashByNameRaw(module interface{}, version interface{}) *pluginStorerGetHashByNameCall {
	return _c.Parent.OnGetHashByNameRaw(module, version)
}

func (_c *pluginStorerUpdateCall) OnListRaw(bParam interface{}) *pluginStorerListCall {
	return _c.Parent.OnListRaw(bParam)
}

func (_c *pluginStorerUpdateCall) OnSearchByNameRaw(bParam interface{}, cParam interface{}) *pluginStorerSearchByNameCall {
	return _c.Parent.OnSearchByNameRaw(bParam, cParam)
}

func (_c *pluginStorerUpdateCall) OnUpdateRaw(bParam interface{}, cParam interface{}) *pluginStorerUpdateCall {
	return _c.Parent.OnUpdateRaw(bParam, cParam)
}

// goproxyPluginClientMock mock of GoproxyPluginClient.
type goproxyPluginClientMock struct{ mock.Mock }

// NewGoproxyPluginClientMock creates a new goproxyPluginClientMock.
func NewGoproxyPluginClientMock(tb testing.TB) *goproxyPluginClientMock {
	tb.Helper()

	m := &goproxyPluginClientMock{}
	m.Mock.Test(tb)

	tb.Cleanup(func() { m.AssertExpectations(tb) })

	return m
}

func (_m *goproxyPluginClientMock) DownloadSources(moduleName string, version string) (io.ReadCloser, error) {
	_ret := _m.Called(moduleName, version)

	if _rf, ok := _ret.Get(0).(func(string, string) (io.ReadCloser, error)); ok {
		return _rf(moduleName, version)
	}

	_ra0, _ := _ret.Get(0).(io.ReadCloser)
	_rb1 := _ret.Error(1)

	return _ra0, _rb1
}

func (_m *goproxyPluginClientMock) OnDownloadSources(moduleName string, version string) *goproxyPluginClientDownloadSourcesCall {
	return &goproxyPluginClientDownloadSourcesCall{Call: _m.Mock.On("DownloadSources", moduleName, version), Parent: _m}
}

func (_m *goproxyPluginClientMock) OnDownloadSourcesRaw(moduleName interface{}, version interface{}) *goproxyPluginClientDownloadSourcesCall {
	return &goproxyPluginClientDownloadSourcesCall{Call: _m.Mock.On("DownloadSources", moduleName, version), Parent: _m}
}

type goproxyPluginClientDownloadSourcesCall struct {
	*mock.Call
	Parent *goproxyPluginClientMock
}

func (_c *goproxyPluginClientDownloadSourcesCall) Panic(msg string) *goproxyPluginClientDownloadSourcesCall {
	_c.Call = _c.Call.Panic(msg)
	return _c
}

func (_c *goproxyPluginClientDownloadSourcesCall) Once() *goproxyPluginClientDownloadSourcesCall {
	_c.Call = _c.Call.Once()
	return _c
}

func (_c *goproxyPluginClientDownloadSourcesCall) Twice() *goproxyPluginClientDownloadSourcesCall {
	_c.Call = _c.Call.Twice()
	return _c
}

func (_c *goproxyPluginClientDownloadSourcesCall) Times(i int) *goproxyPluginClientDownloadSourcesCall {
	_c.Call = _c.Call.Times(i)
	return _c
}

func (_c *goproxyPluginClientDownloadSourcesCall) WaitUntil(w <-chan time.Time) *goproxyPluginClientDownloadSourcesCall {
	_c.Call = _c.Call.WaitUntil(w)
	return _c
}

func (_c *goproxyPluginClientDownloadSourcesCall) After(d time.Duration) *goproxyPluginClientDownloadSourcesCall {
	_c.Call = _c.Call.After(d)
	return _c
}

func (_c *goproxyPluginClientDownloadSourcesCall) Run(fn func(args mock.Arguments)) *goproxyPluginClientDownloadSourcesCall {
	_c.Call = _c.Call.Run(fn)
	return _c
}

func (_c *goproxyPluginClientDownloadSourcesCall) Maybe() *goproxyPluginClientDownloadSourcesCall {
	_c.Call = _c.Call.Maybe()
	return _c
}

func (_c *goproxyPluginClientDownloadSourcesCall) TypedReturns(a io.ReadCloser, b error) *goproxyPluginClientDownloadSourcesCall {
	_c.Call = _c.Return(a, b)
	return _c
}

func (_c *goproxyPluginClientDownloadSourcesCall) ReturnsFn(fn func(string, string) (io.ReadCloser, error)) *goproxyPluginClientDownloadSourcesCall {
	_c.Call = _c.Return(fn)
	return _c
}

func (_c *goproxyPluginClientDownloadSourcesCall) TypedRun(fn func(string, string)) *goproxyPluginClientDownloadSourcesCall {
	_c.Call = _c.Call.Run(func(args mock.Arguments) {
		_moduleName := args.String(0)
		_version := args.String(1)
		fn(_moduleName, _version)
	})
	return _c
}

func (_c *goproxyPluginClientDownloadSourcesCall) OnDownloadSources(moduleName string, version string) *goproxyPluginClientDownloadSourcesCall {
	return _c.Parent.OnDownloadSources(moduleName, version)
}

func (_c *goproxyPluginClientDownloadSourcesCall) OnGetModFile(moduleName string, version string) *goproxyPluginClientGetModFileCall {
	return _c.Parent.OnGetModFile(moduleName, version)
}

func (_c *goproxyPluginClientDownloadSourcesCall) OnDownloadSourcesRaw(moduleName interface{}, version interface{}) *goproxyPluginClientDownloadSourcesCall {
	return _c.Parent.OnDownloadSourcesRaw(moduleName, version)
}

func (_c *goproxyPluginClientDownloadSourcesCall) OnGetModFileRaw(moduleName interface{}, version interface{}) *goproxyPluginClientGetModFileCall {
	return _c.Parent.OnGetModFileRaw(moduleName, version)
}

func (_m *goproxyPluginClientMock) GetModFile(moduleName string, version string) (*modfile.File, error) {
	_ret := _m.Called(moduleName, version)

	if _rf, ok := _ret.Get(0).(func(string, string) (*modfile.File, error)); ok {
		return _rf(moduleName, version)
	}

	_ra0, _ := _ret.Get(0).(*modfile.File)
	_rb1 := _ret.Error(1)

	return _ra0, _rb1
}

func (_m *goproxyPluginClientMock) OnGetModFile(moduleName string, version string) *goproxyPluginClientGetModFileCall {
	return &goproxyPluginClientGetModFileCall{Call: _m.Mock.On("GetModFile", moduleName, version), Parent: _m}
}

func (_m *goproxyPluginClientMock) OnGetModFileRaw(moduleName interface{}, version interface{}) *goproxyPluginClientGetModFileCall {
	return &goproxyPluginClientGetModFileCall{Call: _m.Mock.On("GetModFile", moduleName, version), Parent: _m}
}

type goproxyPluginClientGetModFileCall struct {
	*mock.Call
	Parent *goproxyPluginClientMock
}

func (_c *goproxyPluginClientGetModFileCall) Panic(msg string) *goproxyPluginClientGetModFileCall {
	_c.Call = _c.Call.Panic(msg)
	return _c
}

func (_c *goproxyPluginClientGetModFileCall) Once() *goproxyPluginClientGetModFileCall {
	_c.Call = _c.Call.Once()
	return _c
}

func (_c *goproxyPluginClientGetModFileCall) Twice() *goproxyPluginClientGetModFileCall {
	_c.Call = _c.Call.Twice()
	return _c
}

func (_c *goproxyPluginClientGetModFileCall) Times(i int) *goproxyPluginClientGetModFileCall {
	_c.Call = _c.Call.Times(i)
	return _c
}

func (_c *goproxyPluginClientGetModFileCall) WaitUntil(w <-chan time.Time) *goproxyPluginClientGetModFileCall {
	_c.Call = _c.Call.WaitUntil(w)
	return _c
}

func (_c *goproxyPluginClientGetModFileCall) After(d time.Duration) *goproxyPluginClientGetModFileCall {
	_c.Call = _c.Call.After(d)
	return _c
}

func (_c *goproxyPluginClientGetModFileCall) Run(fn func(args mock.Arguments)) *goproxyPluginClientGetModFileCall {
	_c.Call = _c.Call.Run(fn)
	return _c
}

func (_c *goproxyPluginClientGetModFileCall) Maybe() *goproxyPluginClientGetModFileCall {
	_c.Call = _c.Call.Maybe()
	return _c
}

func (_c *goproxyPluginClientGetModFileCall) TypedReturns(a *modfile.File, b error) *goproxyPluginClientGetModFileCall {
	_c.Call = _c.Return(a, b)
	return _c
}

func (_c *goproxyPluginClientGetModFileCall) ReturnsFn(fn func(string, string) (*modfile.File, error)) *goproxyPluginClientGetModFileCall {
	_c.Call = _c.Return(fn)
	return _c
}

func (_c *goproxyPluginClientGetModFileCall) TypedRun(fn func(string, string)) *goproxyPluginClientGetModFileCall {
	_c.Call = _c.Call.Run(func(args mock.Arguments) {
		_moduleName := args.String(0)
		_version := args.String(1)
		fn(_moduleName, _version)
	})
	return _c
}

func (_c *goproxyPluginClientGetModFileCall) OnDownloadSources(moduleName string, version string) *goproxyPluginClientDownloadSourcesCall {
	return _c.Parent.OnDownloadSources(moduleName, version)
}

func (_c *goproxyPluginClientGetModFileCall) OnGetModFile(moduleName string, version string) *goproxyPluginClientGetModFileCall {
	return _c.Parent.OnGetModFile(moduleName, version)
}

func (_c *goproxyPluginClientGetModFileCall) OnDownloadSourcesRaw(moduleName interface{}, version interface{}) *goproxyPluginClientDownloadSourcesCall {
	return _c.Parent.OnDownloadSourcesRaw(moduleName, version)
}

func (_c *goproxyPluginClientGetModFileCall) OnGetModFileRaw(moduleName interface{}, version interface{}) *goproxyPluginClientGetModFileCall {
	return _c.Parent.OnGetModFileRaw(moduleName, version)
}
