name: 📦️ Plugin Service CI

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  main:
    name: Main Process
    runs-on: ubuntu-latest
    env:
      GOLANGCI_LINT_VERSION: 'v2.3.0'

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.2
      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: 'go.mod'

      - name: Check and get dependencies
        run: |
          go mod download
          go mod tidy
          git diff --exit-code go.mod
          git diff --exit-code go.sum

      - name: golangci-lint
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 #v9.2.0
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}